### ISSUE TITLE
a little question about the code

### ISSUE THREAD

**Issue by chaobiubiu** [google-research/episodic-curiosity#1]
In the curiosity_env_wrapper.py, the step_wait function returns postprocessed_rewards. However, I see that postprocessed_rewards = (self._scale_task_reward * rewards +scale_surrogate_reward * bonus_rewards) where scale_surrogate_reward is set to 0. I want to konw how to pass the episodic curiosity reward to the ppo training process. It's likely that I have lost something in reading the code, but I can't solve this problem myself. I am sincerely hoping that you can help me.

**Comment by RaphaelMarinier** [comment]
_scale_surrogate_reward_ and _scale_task_reward_ of CuriosityEnvWrapper are passed as gin-config parameters. If you are not familiar with gin, you can read about it [there](https://github.com/google/gin-config).

In our code, gin parameters are passed by in launcher_script.py. See for instance [this line](https://github.com/google-research/episodic-curiosity/blob/2bdc10dd8f59f2ffe4f910b8f3a6a3476a0dc5a7/scripts/launcher_script.py#L171).

**Comment by chaobiubiu** [comment]
> _scale_surrogate_reward_ and _scale_task_reward_ of CuriosityEnvWrapper are passed as gin-config parameters. If you are not familiar with gin, you can read about it [there](https://github.com/google/gin-config).
> 
> In our code, gin parameters are passed by in launcher_script.py. See for instance [this line](https://github.com/google-research/episodic-curiosity/blob/2bdc10dd8f59f2ffe4f910b8f3a6a3476a0dc5a7/scripts/launcher_script.py#L171).
> 
> (Closing the issue, since this should answer your question)

Thank you.
