### ISSUE TITLE
container for reproducibility

### ISSUE THREAD

**Issue by jerabaul29** [google-research/episodic-curiosity#7]
Do you have / could you release a container, either Docker or Singularity, so that the use willing to reproduce can simply:

- 1 download the container
- 2 cd to the right folder and launch your scripts

without the need to fix the install etc? :)

**Comment by RaphaelMarinier** [comment]
Hello jerabaul29,

We don't provide a container and for now we don't plan to provide one.
Installation instructions are fairly detailed. We are happy to help if you encounter issues specific to episodic-curiosity that you don't manage to solve.
